package com.springboot.mysql_driver.controller;

import com.springboot.mysql_driver.entity.User;
import com.springboot.mysql_driver.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

// This means that this class is a Controller
@Controller
// This means URL's start with /demo (after Application path)
@RequestMapping(path = "/main")
public class MainController {

    /**
     * This means to get the bean called userRepository
     * Which is auto-generated by Spring, we will use it to handle the data
     */
    @Autowired
    private UserRepository userRepository;

    /**
     * Map ONLY POST Requests
     *
     * @param name
     * @param email
     * @return
     */
    @PostMapping(path = "/add")
    public @ResponseBody
    String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.out.println("addNewUser：" + name + "：" + email);
        User n = new User(name, email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        System.out.println("getAllUsers");
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
